env:
  browser: true
  es2021: true
  jest: true

extends:
  - airbnb-base

parserOptions:
  requireConfigFile: false
  ecmaVersion: latest
  sourceType: module
# rules:
#   object-curly-newline:
#     - error
#     - ImportDeclaration: never
#       ExportDeclaration: never
#   object-curly-spacing:
#     - error
#     - never
#   no-underscore-dangle:
#     - error
#     - allowAfterThis: true
#   max-len:
#     - error
#     - 120
#   import/extensions:
#     - error
#     - ignorePackages
#     - js: never
